### ISSUE TITLE
Questions about the design

### ISSUE THREAD

**Issue by zhuzhujulie** [utopia-group/sypet#2]
Hi, why do you need blacklist, poly, and buildingPkg??

**Comment by fredfeng** [comment]
The idea is to restrict the size of the Petri net thus make the tool more scalable in practice.

#Config file (CONFIG.json)

*blacklist: SyPet will not include those methods in the PetriNet

*poly: Specify sub-typing relationship on-demand

*buildinPkg: Build-in packages included by SyPet

**Comment by zhuzhujulie** [comment]
Thank you !!!
Sorry to see your answer till today. You are right, 
the error comes from the "config.json",
can you tell me what does the variable
“localMax” represents for??
By the way, will you consider open the source code of hunter in the future??

**Comment by rubengmartins** [comment]
The variable "localMax" is used to specify the length of the program you are looking for. You can start by searching for programs of size 1 and then iteratively increase the size until a program has been found.

Hunter was developed as part of a larger project and at the moment there is no plans to release it as open source. We plan to continue to improve SyPet and release SyPet 2.0 during the next year.
